#!/bin/sh

. "$HOME/.profile"

setxkbmap gb

randr > "$HOME/.dwm/log" 2>&1

while true
do
    NETWORK=`network`
    BATTERY=`battery`
    DATE=`date "+[%a] %F %T"`
    LAYOUT=`setxkbmap -query | awk '/^layout:/ {print $2}'`
    DWM_STATUS="net: $NETWORK bat: $BATTERY $LAYOUT $DATE"

    xsetroot -name "$DWM_STATUS"
    sleep 1
done &
